- name: PLAY déploiement docker-compose
  hosts: hedgedoc
  tasks:
    - name: Installation prérequis python
      ansible.builtin.apt:
        name: ['python', 'python3-pip','python-setuptools']

    - name: Install and upgrade pip
      pip:
        name: pip
        extra_args: --upgrade
        executable: pip3
        
    - name: installation docker et docker-compose
      ansible.builtin.pip:
        name: ['docker-compose', 'docker']
        executable: pip3


      
    - name: checkout git
      ansible.builtin.git:
        repo: "https://github.com/davidchdebray/hedgedoc_mariadb.git"
        dest: /home/stagiaire/Entreprise2fifou
        single_branch: yes
        version: main
        force: yes

    - name: deploiement docker-compose
      community.docker.docker_compose:
        project_src: /home/stagiaire/Entreprise2fifou/
      register: output
