- name: PLAY déploiement docker-compose

  hosts: hedgedoc

  vars_files:
    - myvars.yml

  tasks:
    - name: Installation prérequis python
      ansible.builtin.apt:
        name: ['python', 'python3-pip','python-setuptools']
        
    - name: installation docker et docker-compose
      ansible.builtin.pip:
        name: ['docker-compose', 'docker']
        executable: pip3   
     
    - name: checkout git
      ansible.builtin.git:
        repo: "{{app_git}}"
        dest: "{{app_path}}/git"
#        single_branch: yes
#        version: main
        force: yes
      tags: always


    - name: deploiement docker-compose
      community.docker.docker_compose:
        project_name: "{{file_name}}"
        project_src: "{{app_path}}/git/"
        restarted: yes
        state: present
      register: output

