- name: PLAY déploiement docker-compose
  hosts: davidtest
  tasks:
    - name: Installation prérequis python
      ansible.builtin.apt:
        name: ['python', 'python3-pip','python-setuptools']

    - name: Install and upgrade pip
      pip:
        name: pip
        extra_args: --upgrade
        executable: pip3
        
    - name: installation docker et docker-compose
      ansible.builtin.pip:
        name: ['docker-compose', 'docker']
        executable: pip3


    - name: checkout git
      ansible.builtin.git:
        repo: "https://github.com/davidchdebray/hedgedoc_mariadb.git"
        dest: /home/stagiaire/ProjetCapGemini/DOCUMENTATION
        # single_branch: yes
        # version: main
        force: yes
      tags: always

    - name: deploiement docker-compose
      community.docker.docker_compose:
        project_name: "HedgeDoc_MariaDB"
        project_src: /home/stagiaire/ProjetCapGemini/DOCUMENTATION
        restarted: yes
        state: present
      register: output
