- name: PLAY déploiement docker-compose
  hosts: hedgedoc
  tasks:
    - name: installer les prérequis python
      ansible.builtin.apt:
        name: python3-pip

    - name: installation des librairies python
      ansible.builtin.pip:
        name: docker
        executable: pip3
      
    - name: checkout git
      ansible.builtin.git:
        repo: "https://github.com/davidchdebray/hedgedoc_mariadb.git"
        dest: /home/stagiaire/Entreprise2fifou
        single_branch: yes
        version: main
        force: yes

    - name: deploiement docker-compose
      community.docker.docker_compose:
        project_src: /home/stagiaire/Entreprise2fifou/
      register: output
